---
title: "phyloseq"
author: "Hadrien Gourlé"
date: "3/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_pkgs}
library(dada2)
library(phyloseq)
library(ggplot2)
library(readr)
library(ggsci)
library(phangorn)
library(DECIPHER)
```

```{r load_data}
load("results/seqtab.nochim")
load("results/taxa")
samples.out <- rownames(seqtab.nochim)
metadata <- read_csv("data/samples.txt")
row.names(metadata) <- metadata$run
```

```{r tree}
sequences <- getSequences(seqtab.nochim)
names(sequences) <- sequences
alignment <- AlignSeqs(DNAStringSet(sequences), anchor=NA)

phang_align <- phyDat(as(alignment, 'matrix'), type='DNA')
dm <- dist.ml(phang_align)
treeNJ <- NJ(dm)  # note, tip order != sequence order
fit = pml(treeNJ, data=phang_align)

## negative edges length changed to 0!

fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model='GTR', optInv=TRUE, optGamma=TRUE,
                    rearrangement = 'stochastic',
                    control = pml.control(trace = 0))
detach('package:phangorn', unload=TRUE)
```

```{r}
View(metadata)
```


```{r}
physeq <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE),
                   sample_data(metadata),
                   tax_table(taxa),
                   phy_tree(fitGTR$tree))
# remove mock sample
physeq
```

```{r}
plot_richness(physeq, x = "run", color = "sample", measures = c('Fisher')) +
    theme_minimal()
```

```{r}
str(physeq@tax_table)
top20 <- names(sort(taxa_sums(physeq), decreasing=TRUE))[1:20]
physeq_top20 <- transform_sample_counts(physeq, function(OTU) OTU/sum(OTU))
physeq_top20 <- prune_taxa(top20, physeq_top20)
plot_bar(physeq, x='run', fill='Phylum') +
    theme_minimal()
```

```{r}
# tree doesn't seem too bad
proteo <- subset_taxa(physeq, Phylum %in% c('Cyanobacteria'))
plot_tree(proteo, ladderize='left', size='abundance',
          color='sample', label.tips='Genus')
```

